### ISSUE TITLE
flip order of chapters 5 and 6?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2-archive#103]
This is what I do now with my course (https://github.com/nature-of-code/noc-syllabus-S20) and it might work nicely for the book.

**Comment by sidwellr** [comment]
It does make sense. Chapters 2-4 implement custom physics, inspired by the natural world but taking a lot of liberties to simplify things. The Physics Libraries chapter shows how to make things more realistic and particularly dealing with collisions. Then the Autonomous Agents chapter ignores physics libraries and goes back to custom physics. In the first example, "Seeking a target" the seeker just passes through the target with no collision. So the Autonomous Agents chapter is much more like chapters 2-4 and logically follows from them.

Putting Autonomous Agents before Physics Libraries also opens the possibility of showing how to include autonomous behavior when using a physics library. Perhaps even the expectation of doing so. This will make the Physics Libraries chapter more complicated. How does one incorporate flow fields in Box2D? But it will also make that chapter more useful!

**Comment by shiffman** [comment]
It's happening!!!
