### ISSUE TITLE
A Better Way to Write the book mdx

### ISSUE THREAD

**Issue by maan2003** [nature-of-code/noc-book-2-archive#105]
I have been working on [mdx](https://mdxjs.com) based content it look a lot cleaner.
I have build a script that convert that converts html content to mdx.
and one that convert mdx to html at build time.

![image](https://user-images.githubusercontent.com/49202620/77242201-ecc0cb80-6c21-11ea-87ac-61003232d2eb.png)
 Do you wish to use it.

**Comment by shiffman** [comment]
@43-stuti this is an interesting suggestion and related to our workflow discussions! Thank you @Maan2003, we are considering moving the book source files to different formats!

**Comment by shiffman** [comment]
Thank you @Maan2003 for this wonderful suggestion! I've got a whole new system going in https://github.com/nature-of-code/book-website-2nd-edition. I am now writing the book in Notion. It's a great deal more complex than mdxjs and probably doesn't generalize as well, but it's working for me and pushing the project forward!
