### ISSUE TITLE
How was the book produced?

### ISSUE THREAD

**Issue by ofenerci** [nature-of-code/noc-book-2-archive#110]
For a translation purposes of the book,  I wonder how the book was produced? (i.e, which editor used, etc.)  There is a content directory in the github's page of the book and all chapters are html file. Has all the book been written in html? Is there a source code in simple markdown?

**Comment by shiffman** [comment]
Let's make sure we update and include documentation in this repo's README as we revisit the build process for the book!

**Comment by shiffman** [comment]
Everything is now happening in https://github.com/nature-of-code/book-website-2nd-edition Stay tuned!
