### ISSUE TITLE
Missing Chapter 5

### ISSUE THREAD

**Issue by firatbatar** [nature-of-code/noc-book-2-archive#119]
In build1 and build2 there is no chapter 5. It's skipping to chapter 6. Is it removed for some reason or did i messed something?

![build2](https://user-images.githubusercontent.com/55570587/103504040-520b4380-4e67-11eb-9100-8ba075d56d4d.PNG)
![build1](https://user-images.githubusercontent.com/55570587/103504041-533c7080-4e67-11eb-89df-ee8642b9a3ef.PNG)

**Comment by shiffman** [comment]
Chapter 5 is now 6 (and 6 is now 5) and is being rewritten! https://github.com/nature-of-code/book-website-2nd-edition
