### ISSUE TITLE
Dead(ish) Link in Chapter 9

### ISSUE THREAD

**Issue by MpdWalsh** [nature-of-code/noc-book-2-archive#124]
https://natureofcode.com/book/chapter-9-the-evolution-of-code/#chapter09_exercise12

The example suggests checking out [BoxCar2D](http://boxcar2d.com) but that page requires Adobe Flash Player.

**Comment by shiffman** [comment]
This chapter is being entirely rewritten with matter.js so a new reference will have to be chosen!
