### ISSUE TITLE
Chapter 1  no display method but show

### ISSUE THREAD

**Issue by maybeflush** [nature-of-code/noc-book-2-archive#128]
hi thank you for this work.
Reading chapt 1 of noc2,  i've noticed some stuffs:
void step() function is indeed an instance of Walker Class, isnt it? then u ve to modify x to this.x and y to this.y ?
Besides, there's no display() method in this class but show(), so it has to be changed when calling the draw function.
Cheers.
Maybeflush from Paris

**Comment by shiffman** [comment]
Fixed!
