### ISSUE TITLE
HTML build notes

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2-archive#19]
Hi @nelliemckesson I was writing you an e-mail but thought maybe best to write out my notes on the HTML build here (just did a pass over it). You are probably aware of most of these!

1. I could revamp the website, but I would prefer to keep the same urls. I would like to book to build to:

```
chapter-1-vectors/index.html
chapter-2-forces/index.html
etc...
```

rather than the current:

```
vectors.html
forces.html
etc...
````

2. The JS files (and everything necessary for `/book/` specifically fonts, css, etc) should get included in the build. . and end up in the assets folder? Something like:

```
assets/javascript/size-iframes.js
etc.
```

Then the template should reference their relative path so that it can be tested without being published to the site itself? ...and anything that is part of `natureofcode.com` (not in the `/book/`) directly can be referenced via the full url?

The goal is to be able to open up `/build2/` and have it look exactly like `natureofcode.com/book/`. Does that make sense?

3. Syntax highlighting (maybe [prism](https://prismjs.com/)?), I wonder what @runemadsen uses for his book?

4. Code splitting.

5. The layout looks off to me when I open the build, but this might be due to various path things that aren't set up correctly as in (2) above.

<img width="1233" alt="screen shot 2018-08-27 at 8 50 08 pm" src="https://user-images.githubusercontent.com/191758/44694329-d305d500-aa3a-11e8-8a57-7faea65ffc28.png">

**Comment by joeyklee** [comment]
@shiffman - just noting a thing that might be related either to the `magicbook` build defaults or the `magicbook.config`. 

After building, the PDF build expects the `css` styles to live in `build/assets/`. Since the builds for each context `html` vs `pdf` get built into `build1` and `build2`, magicbook isn't getting the styles that it expects. 

e.g.

<img width="1112" alt="Screen Shot 2019-06-24 at 18 08 37" src="https://user-images.githubusercontent.com/3622055/60055457-b0206d80-96ab-11e9-83d0-28a3d580e48b.png">

in **error.txt**
```
Mon Jun 24 17:30:25 2019: build/assets/katex.css: warning: can't open input file: No such file or directory
Mon Jun 24 17:30:25 2019: build/assets/pdf.css: warning: can't open input file: No such file or directory
Mon Jun 24 17:30:33 2019: finished: success
```

**Comment by joeyklee** [comment]
The above explains why the images in the PDF aren't properly sized. 

Ideally we'd have:

<img width="1453" alt="Screen Shot 2019-06-24 at 18 14 32" src="https://user-images.githubusercontent.com/3622055/60055562-0097cb00-96ac-11e9-8160-4f57449217bd.png">


But right now it looks more like:

<img width="900" alt="Screen Shot 2019-06-24 at 18 15 39" src="https://user-images.githubusercontent.com/3622055/60055590-1c02d600-96ac-11e9-818d-b75904204530.png">

**Comment by joeyklee** [comment]
The above is related to: https://github.com/nature-of-code/noc-book/pull/159#issuecomment-505087729

**Comment by shiffman** [comment]
@jasongao97 as you are working on the HTML build, could you check if any of the above discussion is still an issue or if this can be closed? Thank you!! @43-stuti there are also some interesting historical notes about the workflow here!

**Comment by shiffman** [comment]
Closing this issue, please see all new progress and build system in https://github.com/nature-of-code/book-website-2nd-edition/ Woohoo!
