### ISSUE TITLE
Is &lt; required in embedded code examples?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2-archive#22]
In previous builds of the book, using a `<` in a code example broke the rendering process given its meaning in HTML. Visual Studio Code colors it red to show it is unclosed:

<img width="940" alt="Screen Shot 2019-06-25 at 11 36 25 AM" src="https://user-images.githubusercontent.com/191758/60112264-7bf58d00-973d-11e9-8e25-3bd2d84ce643.png">

My solution is to manually replace with `&lt;`. Is this still required? It would be a bit easier in terms of copy/pasting between things to use `<`.

```
  for (let i = 0; i &lt; 20; i++) {
    randomCounts[i] = 0; 
  }
```

**Comment by joeyklee** [comment]
@shiffman - ooh! That's a pain. I will look into this.

**Comment by joeyklee** [comment]
@shiffman - I did a few quick changes and converted the `&lt;` to `<` and the page seems to build correctly:

<img width="1264" alt="Screen Shot 2019-06-25 at 12 37 15" src="https://user-images.githubusercontent.com/3622055/60116459-0b9f3980-9746-11e9-8e2d-780fd9f4b3f6.png">
<img width="661" alt="Screen Shot 2019-06-25 at 12 36 22" src="https://user-images.githubusercontent.com/3622055/60116465-0e9a2a00-9746-11e9-9fc4-bb7d4cc7f001.png">

**Comment by shiffman** [comment]
Hi @jasongao97 it would be great if we could test this then do a global find/replace to use `<` and `>` in the code examples instead of `&lt;` and `&gt;`

**Comment by shiffman** [comment]
This is resolved with the new workflow / build system
