### ISSUE TITLE
Force of the pendulum

### ISSUE THREAD

**Issue by Jordan2R** [nature-of-code/noc-book-2-archive#3]
When you start saying about the force of the pendulum at chapter 3 (oscillation), you wrote "Since the force of gravity (Fp) points downward...". It shoud be "Since the force of gravity (Fg) points downward..."

**Comment by Jordan2R** [comment]
Also, the picture says that sin(theta) = Fg/Fp, when you wrote yourself it should be Fp/Fg

**Comment by shiffman** [comment]
Closing this issue, I have a separate one for the illustration!!
