### ISSUE TITLE
Define new indexing terms

### ISSUE THREAD

**Issue by joeyklee** [nature-of-code/noc-book-2-archive#38]
At the moment there are indexing terms that will need to be updated. Just making a note here about making sure to do so:

for example:
```html
<a
      data-primary="Processing"
      data-secondary="vectors and"
      data-type="indexterm"
    ></a>
    <a data-primary="PVector class (Processing)" data-type="indexterm"></a>
    <a
      data-primary="vectors"
      data-secondary="Processing and"
      data-type="indexterm"
    ></a>
```

**Comment by shiffman** [comment]
I noticed this too. I'm assuming that the index will be handled by an indexing expert at the end when all is said and done. So I am choosing to ignore this at the moment. I suppose we could update what we know needs to be updated. I'm not sure. I'll have to start researching some indexing company. Last time I used this company http://www.wordco.com/

**Comment by joeyklee** [comment]
No problem. Let's just keep an eye on this for now. As we work our way through the content I guess we'll start to converge on a good way of changing the index terms.

**Comment by shiffman** [comment]
New index will be commissioned at the end of the process after final text is completed.
