### ISSUE TITLE
PVector ==> p5.Vector in text?

### ISSUE THREAD

**Issue by joeyklee** [nature-of-code/noc-book-2-archive#39]
A question about terminology:

* Do we explicitly use: `p5.Vector()` to create vectors or rather `createVector()`?
* In the text do we replace `PVector` with `p5.Vector`?

**Comment by shiffman** [comment]
`createVector()` should definitely be used! (There is no equivalent in Processing). I think I will probably go between saying explicitly `p5.Vector` and just "vector" when writing more generally about a vector object. I'll have to think about this a bit more.

**Comment by joeyklee** [comment]
Sounds good. In the beginning when you introduce vector operations, there's a kind of back and forth between brewing up your own vector class and showing how it works in p5. I did a first pass in https://github.com/nature-of-code/noc-book-2/pull/28 and hopefully it make sense :)

**Comment by shiffman** [comment]
Noting that in a lot of cases where I previously save "PVector" it makes more sense to refer to them as  lower-case "vector" or "vectors." `p5.Vector` can be reserved for special cases specific to p5 implementation itself. Reflecting this in my pass over Chapter 1.

**Comment by shiffman** [comment]
These are being fixed during the editing and re-writing process
