### ISSUE TITLE
Is this the version I get when I order the print version?

### ISSUE THREAD

**Issue by Klendat** [nature-of-code/noc-book-2-archive#48]
I've been meaning to order the print version of this book.

If I order it now does it get printed directly from this repo?

**Comment by joeyklee** [comment]
Hi @Klendat - I believe that if you decide to order the print version of the book, you will get the **old** version that is on the web https://natureofcode.com/ which uses Processin. As a result, I'd recommend waiting a couple months so you can get the new and improved Nature of Code 2nd Edition with p5.js when we're done :)  

I think @shiffman would have similar feedback. This is great motivation to finish faster!

**Comment by shiffman** [comment]
Well, almost 3 years later I am replying to this! I have a goal to complete the 2nd edition with p5.js by the end of 2022! (I'm on sabbatical this year so it should finally be realistic to do so.)
