### ISSUE TITLE
Notes for general things to update

### ISSUE THREAD

**Issue by joeyklee** [nature-of-code/noc-book-2-archive#51]
A note on general things I'm updating as I go along:
* `data-code-language="java"` ==> `data-code-language="javascript"`
* `void setup` ==> `function setup`
* `void draw` ==> `function draw`
* where appropriate: `size()` ==> `createCanvas()` 
* `Processing` ==> `p5.js`
* `PVector` ==> `p5.Vector` or `createVector()` depending on context
* `println()` ==> `print()`
* `pushMatrix()` ==> `push()`
* `popMatrix()` ==> `pop()`
* `PImage`==> `p5.image`

**Comment by shiffman** [comment]
Code examples updated!
