### ISSUE TITLE
Chapter 4, section 3+ use of ArrayList?

### ISSUE THREAD

**Issue by joeyklee** [nature-of-code/noc-book-2-archive#52]
@shiffman - for Chapter 4, sections 4.3+, currently is using the java `ArrayList`. The current JavaScript examples use -- https://github.com/nature-of-code/noc-examples-p5.js/blob/master/chp04_systems/NOC_4_02_ArrayParticles/sketch.js -- use javascript arrays. Just making a special note to make sure to go through those sections. I will add my commits on this in the PR and you can keep or trash them as you see fit. Thanks!

**Comment by shiffman** [comment]
Initial rewrites completed!
