### ISSUE TITLE
[Content Overview] Content Todos

### ISSUE THREAD

**Issue by joeyklee** [nature-of-code/noc-book-2-archive#53]
| Chpt. No | Chapter | First Pass | Second Pass | Third Pass | Final Review |
| -------- | -------- | -------- | -------- | -------- | -------- |
| 00  | welcome | ✅ - @joeyklee  | ☑️ | ☑️ | ☑️ |
| 00  | titlepage | ✅ - @joeyklee | ☑️ | ☑️ | ☑️ |
| 00  | dedication | ✅ - @joeyklee | ☑️ | ☑️ | ☑️ |
| 00  | creditscopyright | ✅ - @joeyklee | ☑️ | ☑️ | ☑️ |
| 00  | acknowledgements | ✅ - @joeyklee | ☑️ | ☑️ | ☑️ |
| 00  | preface | ✅ - @joeyklee | ☑️ | ☑️ | ☑️ |
| 00  | toc | ✅ - @joeyklee | ☑️ | ☑️ | ☑️ |
| 00  | introduction | ✅ - @shiffman  | ☑️ | ☑️ | ☑️ |
| 01  | vectors | ✅ - @joeyklee | ✅ - @shiffman | ✅ - Merged, @joeyklee  | ☑️ |
| 02  | forces | ✅ - @joeyklee | ✅ - @shiffman | ☑️ - Needs Review by @shiffman  | ☑️ |
| 03  | oscillation | ✅ - @joeyklee | ✅ - @shiffman | ☑️ - Needs Review by @shiffman | ☑️ |
| 04  | particles | ✅ - @joeyklee | ☑️ - in progress, @shiffman | ☑️ | ☑️ |
| 05  | physicslib | ☑️ | ☑️ | ☑️ | ☑️ |
| 06  | steering | ✅ - @joeyklee  | ☑️ | ☑️ | ☑️ |
| 07  | cellularautomata | ✅ - @joeyklee| ☑️ | ☑️ | ☑️ |
| 08  | fractals | ✅ - @joeyklee | ☑️ | ☑️ | ☑️ |
| 09  | geneticalgorithms |  ✅ - @joeyklee | ☑️ | ☑️ | ☑️ |
| 10  | neuralnetworks | ✅ - @joeyklee | ☑️ | ☑️ | ☑️ |
| 11  | neuralevolution (?) | ☑️ | ☑️ | ☑️ | ☑️ |
| xx  | furtherreading | ✅ - @joeyklee | ☑️ | ☑️ | ☑️ |
| xx  | allmath | ☑️ | ☑️ | ☑️ | ☑️ |
| xx  | index | ☑️ | ☑️ | ☑️ | ☑️ |

**Comment by shiffman** [comment]
Thank you for this very useful guide @joeyklee, closing this issue as work has all moved to https://github.com/nature-of-code/book-website-2nd-edition/
