### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by klmendor** [nature-of-code/noc-book-2-archive#65]
You see, I forked this repo to make a translation of this book. I'm wondering how would be better? I make a pull request every so often, or I make a whole thing and make one pull request.

**Comment by shiffman** [comment]
Hi @klmendor, sorry this was never responded to. All work is now ongoing in https://github.com/nature-of-code/book-website-2nd-edition/ and hopefully there will be a way to do translations once it is completed.
