### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by fernandogregor-io** [nature-of-code/noc-book-2-archive#89]
page 4 is missing "this before x and y":
`if (choice == 0) {
  x++;
} else if (choice == 1) {
  x--;
} else if (choice == 2) {
  y++;
} else { y--;
}`

page 5 - should be "show" instead of "display"
`walker.step(); Call functions on the Walker. walker.display();`

(let me know if I'm mistaken, please)

**Comment by shiffman** [comment]
Corrected! Only 2.5 years later!!
