### ISSUE TITLE
Use cascidia-code as source code font

### ISSUE THREAD

**Issue by ghost** [nature-of-code/noc-book-2-archive#96]
See the Difference
![image](https://user-images.githubusercontent.com/60620929/75090276-3963a900-5587-11ea-8c27-89e3289fbbc4.png)
![image](https://user-images.githubusercontent.com/60620929/75090284-45e80180-5587-11ea-8291-e1c5116602b7.png)

**Comment by shiffman** [comment]
Thank you for this! The book is now undergoing a new design process so I will definitely take this into consideration!
